name: python version test action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linter-and-formatter:
    runs-on: ubuntu-latest
    steps:
      #       - uses: actions/checkout@v4
      #         with:
      #           ref: ${{ github.event.pull_request.head.sha || env.deploy_TAG }}
      #       - uses: actions/setup-python@v5
      #         id: setup-python
      #         with:
      #           python-version-file: ".python-version"

      - name: Get python version
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version-file: ".python-version"

      - name: Print python version
        run: echo "python-version=${{ steps.setup-python.outputs.python-version }}" >> $GITHUB_OUTPUT
